FROM nginx:alpine

WORKDIR /var/www/html/
COPY . /var/www/html/

RUN mkdir /etc/nginx/sites-enabled \
    && rm /etc/nginx/nginx.conf \
    && ln -s /var/www/html/docker/production/nginx/sites-enabled/* /etc/nginx/sites-enabled/. \
    && ln -s /var/www/html/docker/production/nginx/nginx.conf /etc/nginx/nginx.conf
